var my_tree_data = [
        {
            id: 1,
            parentId: null,
            name: "MI-1000000",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 17400,
            right: "Баллы в правой " + 0,
            full_name: " ",
            image: "/media/images/user.png",
            left_node: 2,
            right_node: 3
        },
        {
            id: 2,
            parentId: 1,
            name: "MI-1000001",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company 1 company 1",
            image: "/media/images/user.png",
            left_node: 4,
            right_node: 5
        },
        {
            id: 4,
            parentId: 2,
            name: "MI-1000003",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-3 company-3",
            image: "/media/images/user.png",
            left_node: 8,
            right_node: 9
        },
        {
            id: 8,
            parentId: 4,
            name: "MI-1000007",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-7 company-7",
            image: "/media/images/user.png",
            left_node: 16,
            right_node: null
        },
        {
            id: 16,
            parentId: 8,
            name: "MI-1000015",
            package: "Бизнес",
            not_active: true,
            left: "Баллы в левой " + 11800,
            right: "Баллы в правой " + 0,
            full_name: "Dominion DOMINION",
            image: "/media/images/user.png",
            left_node: 36,
            right_node: 46
        },
        {
            id: 36,
            parentId: 16,
            name: "MI-1000035",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 1600,
            right: "Баллы в правой " + 3200,
            full_name: "Pozharitskiy Alexander",
            image: "/media/images/user.png",
            left_node: 37,
            right_node: 39
        },
        {
            id: 37,
            parentId: 36,
            name: "MI-1000036",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 3700,
            right: "Баллы в правой " + 0,
            full_name: "Damarod Aliaksandr",
            image: "/media/images/Y0i9VM9I63CKtXazGmEOBe4ilcYYyufsmECpTFyo.jpg",
            left_node: 38,
            right_node: null
        },
        {
            id: 38,
            parentId: 37,
            name: "MI-1000037",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 2400,
            right: "Баллы в правой " + 300,
            full_name: "Липовецкий Егор",
            image: "/media/images/sUGmWNOAR81lyhbC5n3YpmAMrK4LQIZ4K6zKxVpb.jpg",
            left_node: 43,
            right_node: 81
        },
        {
            id: 43,
            parentId: 38,
            name: "MI-1000042",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 2300,
            right: "Баллы в правой " + 0,
            full_name: "Шатро Эрнесто",
            image: "/media/images/user.png",
            left_node: 45,
            right_node: null
        },
        {
            id: 45,
            parentId: 43,
            name: "MI-1000044",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 1300,
            full_name: "Елшина Инна",
            image: "/media/images/user.png",
            left_node: 54,
            right_node: 105
        },
        {
            id: 54,
            parentId: 45,
            name: "MI-1000054",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Сергей Пархоменко",
            image: "/media/images/lJJVopMbLwznMQXDPelo3aKlAruq5Xh8oLeZzIDz.jpg",
            left_node: 55,
            right_node: null
        },
        {
            id: 55,
            parentId: 54,
            name: "MI-1000058",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Глуховский",
            image: "/media/images/user.png",
            left_node: 58,
            right_node: null
        },
        {
            id: 58,
            parentId: 55,
            name: "MI-1000061",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Игорь Волков",
            image: "/media/images/user.png",
            left_node: 63,
            right_node: null
        },
        {
            id: 63,
            parentId: 58,
            name: "MI-1000066",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Симона Шатро",
            image: "/media/images/user.png",
            left_node: 117,
            right_node: null
        },
        {
            id: 117,
            parentId: 63,
            name: "MI-1000120",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Павел Кривушкин",
            image: "/media/images/user.png",
            left_node: 118,
            right_node: null
        },
        {
            id: 118,
            parentId: 117,
            name: "MI-1000121",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Наталья Рогачева",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 105,
            parentId: 45,
            name: "MI-1000108",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "АЛЕКСАНДР ЕЛШИН",
            image: "/media/images/user.png",
            left_node: 124,
            right_node: 106
        },
        {
            id: 106,
            parentId: 105,
            name: "MI-1000109",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 100,
            right: "Баллы в правой " + 1100,
            full_name: "СВЕТЛАНА ЯНКИНА",
            image: "/media/images/user.png",
            left_node: 115,
            right_node: 107
        },
        {
            id: 107,
            parentId: 106,
            name: "MI-1000110",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 100,
            right: "Баллы в правой " + 0,
            full_name: "СВЕЧНИКОВА ТАТЬЯНА",
            image: "/media/images/user.png",
            left_node: 120,
            right_node: null
        },
        {
            id: 120,
            parentId: 107,
            name: "MI-1000123",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "СВЕЧНИКОВ ИВАН",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 115,
            parentId: 106,
            name: "MI-1000118",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Дмитрий Куку",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 124,
            parentId: 105,
            name: "MI-1000127",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Елена Левадняя",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 81,
            parentId: 38,
            name: "MI-1000084",
            package: "Оптимальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Юлианна Кисиль",
            image: "/media/images/user.png",
            left_node: 97,
            right_node: 101
        },
        {
            id: 97,
            parentId: 81,
            name: "MI-1000100",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Дмитрий Лабохо",
            image: "/media/images/user.png",
            left_node: 99,
            right_node: null
        },
        {
            id: 99,
            parentId: 97,
            name: "MI-1000102",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Черкасов",
            image: "/media/images/user.png",
            left_node: 100,
            right_node: null
        },
        {
            id: 100,
            parentId: 99,
            name: "MI-1000103",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Плаксин",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 101,
            parentId: 81,
            name: "MI-1000104",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Леонид Ким",
            image: "/media/images/user.png",
            left_node: 108,
            right_node: 103
        },
        {
            id: 103,
            parentId: 101,
            name: "MI-1000106",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Маргарита Сосновская",
            image: "/media/images/user.png",
            left_node: 110,
            right_node: 104
        },
        {
            id: 104,
            parentId: 103,
            name: "MI-1000107",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Алексей Коноплев",
            image: "/media/images/user.png",
            left_node: 119,
            right_node: 109
        },
        {
            id: 109,
            parentId: 104,
            name: "MI-1000112",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Юра Мамонов",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 113
        },
        {
            id: 113,
            parentId: 109,
            name: "MI-1000116",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Помещиков",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 114
        },
        {
            id: 114,
            parentId: 113,
            name: "MI-1000117",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Игорь Егоров",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 119,
            parentId: 104,
            name: "MI-1000122",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Manon Kasymbekov",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 110,
            parentId: 103,
            name: "MI-1000113",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Кирилл Семеновых",
            image: "/media/images/user.png",
            left_node: 125,
            right_node: 116
        },
        {
            id: 116,
            parentId: 110,
            name: "MI-1000119",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Елена Дорохина",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 125,
            parentId: 110,
            name: "MI-1000128",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Михаил Домин",
            image: "/media/images/user.png",
            left_node: 127,
            right_node: null
        },
        {
            id: 127,
            parentId: 125,
            name: "MI-1000130",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Надежда Ли",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 108,
            parentId: 101,
            name: "MI-1000111",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Раушания Ким",
            image: "/media/images/user.png",
            left_node: 111,
            right_node: 112
        },
        {
            id: 111,
            parentId: 108,
            name: "MI-1000114",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Роман Андреев",
            image: "/media/images/user.png",
            left_node: 122,
            right_node: 121
        },
        {
            id: 121,
            parentId: 111,
            name: "MI-1000124",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Святослав Бакала",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 122,
            parentId: 111,
            name: "MI-1000125",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Анна Сухарева",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 112,
            parentId: 108,
            name: "MI-1000115",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Игорь Павлов",
            image: "/media/images/user.png",
            left_node: 123,
            right_node: 126
        },
        {
            id: 123,
            parentId: 112,
            name: "MI-1000126",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Инга Корсакова",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 126,
            parentId: 112,
            name: "MI-1000129",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Болеслав Байков",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 39,
            parentId: 36,
            name: "MI-1000038",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Гавриленко Егор",
            image: "/media/images/user.png",
            left_node: 40,
            right_node: null
        },
        {
            id: 40,
            parentId: 39,
            name: "MI-1000039",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 4900,
            full_name: "Vorobets Vasyl",
            image: "/media/images/user.png",
            left_node: 61,
            right_node: 42
        },
        {
            id: 42,
            parentId: 40,
            name: "MI-1000041",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 4100,
            full_name: "Чижов Сергей",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 47
        },
        {
            id: 47,
            parentId: 42,
            name: "MI-1000046",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 2900,
            full_name: "Гавриленко 2 Егор",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 48
        },
        {
            id: 48,
            parentId: 47,
            name: "MI-1000047",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 3000,
            full_name: "Дудник Петр",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 49
        },
        {
            id: 49,
            parentId: 48,
            name: "MI-1000048",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 2900,
            full_name: "Мошковская Елена",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 53
        },
        {
            id: 53,
            parentId: 49,
            name: "MI-1000052",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 1700,
            full_name: "Инесса Егорова",
            image: "/media/images/user.png",
            left_node: 67,
            right_node: 59
        },
        {
            id: 59,
            parentId: 53,
            name: "MI-1000062",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 1600,
            full_name: "Александр Пастушенко",
            image: "/media/images/user.png",
            left_node: 66,
            right_node: 60
        },
        {
            id: 60,
            parentId: 59,
            name: "MI-1000063",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 1600,
            full_name: "Вячеслав Веселов",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 64
        },
        {
            id: 64,
            parentId: 60,
            name: "MI-1000067",
            package: "Премиальный",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 600,
            full_name: "Мария Алдашова",
            image: "/media/images/user.png",
            left_node: 77,
            right_node: 65
        },
        {
            id: 65,
            parentId: 64,
            name: "MI-1000068",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Тимофей Старцев",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 69
        },
        {
            id: 69,
            parentId: 65,
            name: "MI-1000072",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Ольга Шульга",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 70
        },
        {
            id: 70,
            parentId: 69,
            name: "MI-1000073",
            package: "Бизнес",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "INNA IEVSIUKOVA",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 71
        },
        {
            id: 71,
            parentId: 70,
            name: "MI-1000074",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Леонид Перебейнос",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 74
        },
        {
            id: 74,
            parentId: 71,
            name: "MI-1000077",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Leonid Yarmiev",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 75
        },
        {
            id: 75,
            parentId: 74,
            name: "MI-1000078",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Олеся Самотой",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 76
        },
        {
            id: 76,
            parentId: 75,
            name: "MI-1000079",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Сергей Семенов",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 79
        },
        {
            id: 79,
            parentId: 76,
            name: "MI-1000082",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Виктория Тараненко",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 89
        },
        {
            id: 89,
            parentId: 79,
            name: "MI-1000092",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Семенов",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 102
        },
        {
            id: 102,
            parentId: 89,
            name: "MI-1000105",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Шуршилин",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 77,
            parentId: 64,
            name: "MI-1000080",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Светлана Баева",
            image: "/media/images/user.png",
            left_node: 78,
            right_node: null
        },
        {
            id: 78,
            parentId: 77,
            name: "MI-1000081",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Иван Ушаков",
            image: "/media/images/user.png",
            left_node: 90,
            right_node: null
        },
        {
            id: 90,
            parentId: 78,
            name: "MI-1000093",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Владимир Цветков",
            image: "/media/images/user.png",
            left_node: 91,
            right_node: 95
        },
        {
            id: 91,
            parentId: 90,
            name: "MI-1000094",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Ярослава Михайлова",
            image: "/media/images/user.png",
            left_node: 92,
            right_node: null
        },
        {
            id: 92,
            parentId: 91,
            name: "MI-1000095",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Олег Астраханцев",
            image: "/media/images/user.png",
            left_node: 93,
            right_node: null
        },
        {
            id: 93,
            parentId: 92,
            name: "MI-1000096",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Светлана Широкова",
            image: "/media/images/user.png",
            left_node: 94,
            right_node: null
        },
        {
            id: 94,
            parentId: 93,
            name: "MI-1000097",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Клец Александр",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 95,
            parentId: 90,
            name: "MI-1000098",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Игорь Порофиев",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 66,
            parentId: 59,
            name: "MI-1000069",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Елена Палиенко",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 67,
            parentId: 53,
            name: "MI-1000070",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Елизавета Сокол",
            image: "/media/images/user.png",
            left_node: 68,
            right_node: null
        },
        {
            id: 68,
            parentId: 67,
            name: "MI-1000071",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Евгений Мартынов",
            image: "/media/images/user.png",
            left_node: 72,
            right_node: 80
        },
        {
            id: 72,
            parentId: 68,
            name: "MI-1000075",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Сергей Тюменцев",
            image: "/media/images/user.png",
            left_node: 83,
            right_node: null
        },
        {
            id: 83,
            parentId: 72,
            name: "MI-1000086",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Татьяна Мартынова",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 80,
            parentId: 68,
            name: "MI-1000083",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Анна Соколова",
            image: "/media/images/user.png",
            left_node: 85,
            right_node: 82
        },
        {
            id: 82,
            parentId: 80,
            name: "MI-1000085",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Светлана Мартынова",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 84
        },
        {
            id: 84,
            parentId: 82,
            name: "MI-1000087",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Григорий Соколов",
            image: "/media/images/user.png",
            left_node: 87,
            right_node: 86
        },
        {
            id: 86,
            parentId: 84,
            name: "MI-1000089",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Назар Лаппа",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 87,
            parentId: 84,
            name: "MI-1000090",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Валерий Мельников",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 85,
            parentId: 80,
            name: "MI-1000088",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Алексей Соколов",
            image: "/media/images/user.png",
            left_node: 88,
            right_node: null
        },
        {
            id: 88,
            parentId: 85,
            name: "MI-1000091",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Юрий Диев",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 61,
            parentId: 40,
            name: "MI-1000064",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 100,
            right: "Баллы в правой " + 0,
            full_name: "Victor Garkusha",
            image: "/media/images/user.png",
            left_node: 62,
            right_node: null
        },
        {
            id: 62,
            parentId: 61,
            name: "MI-1000065",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Oleksandr Lebed",
            image: "/media/images/ZAgonD8eDSoN6fHh5GLFtsOOICBeIds1nSowQbst.JPG",
            left_node: null,
            right_node: null
        },
        {
            id: 46,
            parentId: 16,
            name: "MI-1000045",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 100,
            full_name: "Волкова Мария",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 50
        },
        {
            id: 50,
            parentId: 46,
            name: "MI-1000049",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Алексей Гордеев",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 51
        },
        {
            id: 51,
            parentId: 50,
            name: "MI-1000050",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Погорелый Виталий",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 52
        },
        {
            id: 52,
            parentId: 51,
            name: "MI-1000051",
            package: "Базовый",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Малый",
            image: "/media/images/user.png",
            left_node: 73,
            right_node: 96
        },
        {
            id: 73,
            parentId: 52,
            name: "MI-1000076",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Юрий Акпаршев",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 96,
            parentId: 52,
            name: "MI-1000099",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Александр Антипенков",
            image: "/media/images/user.png",
            left_node: null,
            right_node: 98
        },
        {
            id: 98,
            parentId: 96,
            name: "MI-1000101",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "Дарина Казарян",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 9,
            parentId: 4,
            name: "MI-1000008",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-8 company-8",
            image: "/media/images/user.png",
            left_node: 18,
            right_node: 19
        },
        {
            id: 18,
            parentId: 9,
            name: "MI-1000017",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-16 company-16",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 19,
            parentId: 9,
            name: "MI-1000018",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-17 company-17",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 5,
            parentId: 2,
            name: "MI-1000004",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-4 company-4",
            image: "/media/images/user.png",
            left_node: 10,
            right_node: 15
        },
        {
            id: 10,
            parentId: 5,
            name: "MI-1000009",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-9 company-9",
            image: "/media/images/user.png",
            left_node: 20,
            right_node: 21
        },
        {
            id: 20,
            parentId: 10,
            name: "MI-1000019",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-18 company-18",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 21,
            parentId: 10,
            name: "MI-1000020",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-19 company-19",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 15,
            parentId: 5,
            name: "MI-1000014",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-13 company-13",
            image: "/media/images/user.png",
            left_node: 22,
            right_node: 23
        },
        {
            id: 22,
            parentId: 15,
            name: "MI-1000021",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-20 company-20",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 23,
            parentId: 15,
            name: "MI-1000022",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-21 company-21",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 3,
            parentId: 1,
            name: "MI-1000002",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-2 company-2",
            image: "/media/images/user.png",
            left_node: 6,
            right_node: 7
        },
        {
            id: 6,
            parentId: 3,
            name: "MI-1000005",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-5 company-5",
            image: "/media/images/user.png",
            left_node: 11,
            right_node: 12
        },
        {
            id: 11,
            parentId: 6,
            name: "MI-1000010",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-10 company-10",
            image: "/media/images/user.png",
            left_node: 24,
            right_node: 25
        },
        {
            id: 24,
            parentId: 11,
            name: "MI-1000023",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-22 company-22",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 25,
            parentId: 11,
            name: "MI-1000024",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-23 company-23",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 12,
            parentId: 6,
            name: "MI-1000011",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-11 company-11",
            image: "/media/images/user.png",
            left_node: 26,
            right_node: 27
        },
        {
            id: 26,
            parentId: 12,
            name: "MI-1000025",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-24 company-24",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 27,
            parentId: 12,
            name: "MI-1000026",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-25 company-25",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 7,
            parentId: 3,
            name: "MI-1000006",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-6 company-6",
            image: "/media/images/user.png",
            left_node: 13,
            right_node: 14
        },
        {
            id: 13,
            parentId: 7,
            name: "MI-1000012",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-12 company-12",
            image: "/media/images/user.png",
            left_node: 28,
            right_node: 29
        },
        {
            id: 28,
            parentId: 13,
            name: "MI-1000027",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-26 company-26",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 29,
            parentId: 13,
            name: "MI-1000028",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-27 company-27",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 14,
            parentId: 7,
            name: "MI-1000013",
            package: "None",
            not_active: false,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-12 company-12",
            image: "/media/images/user.png",
            left_node: 30,
            right_node: 31
        },
        {
            id: 30,
            parentId: 14,
            name: "MI-1000029",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-28 company-28",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        },
        {
            id: 31,
            parentId: 14,
            name: "MI-1000030",
            package: "None",
            not_active: true,
            left: "Баллы в левой " + 0,
            right: "Баллы в правой " + 0,
            full_name: "company-29 company-29",
            image: "/media/images/user.png",
            left_node: null,
            right_node: null
        }
];

var not_active = {};

function traverseTree(orgChart, inputArray) {
    var outputArray = [];

    return traverseNode(orgChart, inputArray, outputArray, inputArray[0].id);
}

function generateRootNode(inputArray) {
    var node = inputArray[0];
    node.fakeId = 0;
    node.fakeParentId = null;

    return JSON.parse(JSON.stringify(node));
}

function getChildId(parentId, isLeftBranch) {
    return parentId * 100000 + isLeftBranch;
}

function mockUnit(parentId, isLeftBranch) {
    var magic = 16777213;
    return {
        id: -1,
        parentId: parentId,
        name: null,
        package: null,
        left: 0,
        right: 0,
        image: null,
        left_node: null,
        right_node: null
    };
}

var nodes_customize = {};


function traverseNode(orgChart, inputArray, outputArray, nodeId, parentId, isLeftBranch) {
    var node = inputArray.find(function (item) {
        return (Number(item.id) === Number(nodeId));
    });
    var mock;

    if (!node) {
        throw new Error('Node ID ' + nodeId + ' is not present!');
    }

    if (node.parentId) {
        node.fakeId = getChildId(node.parentId, isLeftBranch);
        node.fakeParentId = parentId;
        orgChart.insertNode(node.fakeParentId, node, node.fakeId);
    }
    if (node.not_active) {
        nodes_customize[node.fakeId] = {color: "green"};
    }

    if (node.left_node == null) {
        mock = mockUnit(nodeId, 0);
        mock.fakeId = getChildId(node.id, 0);
        nodes_customize[getChildId(node.id, 0)] = {theme: "helen"};
        mock.fakeParentId = node.fakeId;
        orgChart.insertNode(mock.fakeParentId, mock, mock.fakeId);
    } else {
        traverseNode(orgChart, inputArray, outputArray, node.left_node, node.fakeId, 0);
    }

    if (node.right_node == null) {
        mock = mockUnit(nodeId, 1);
        mock.fakeId = getChildId(node.id, 1);
        nodes_customize[getChildId(node.id, 1)] = {theme: "helen"};
        mock.fakeParentId = node.fakeId;
        orgChart.insertNode(mock.fakeParentId, mock, mock.fakeId);
    } else {
        traverseNode(orgChart, inputArray, outputArray, node.right_node, node.fakeId, 1);
    }

    return outputArray;
}

var peopleElement = document.getElementById("tree");
var orgChart = new getOrgChart(peopleElement, {
    color: "neutralgrey",
    gridView: true,
    idField: "fakeId",
    parentIdField: "fakeParentId",
    enableEdit: false,
    enableSearch: false,
    enableDetailsView: false,
    enableZoomOnNodeDoubleClick: true,
    linkType: "M", //"M"
    primaryFields: ["full_name", "name", "package", "left", "right"],
    photoFields: ["image"],
    expandToLevel: 5,
    scale: 0.3,
    dataSource: [generateRootNode(my_tree_data)],
    customize: nodes_customize
});

traverseTree(orgChart, my_tree_data);